[project]
name = "rynth"
version = "0.0.3"
description = "Python bindings for VapourSynth."
readme = "README.md"
license = "EUPL-1.2"
license-files = ["LICENSE.txt"]
requires-python = ">=3.12"

dependencies = ["vapoursynth>=79"]

[dependency-groups]
dev = [
    "flexoki-zensical==0.1.1",
    "maturin==1.14.1",
    "mkdocstrings-python==2.0.7",
    "mypy==2.3.1",
    "numpy==2.5.2",
    "pytest==9.1.1",
    "ruff==0.16.3",
    "zensical==0.0.56",
]

[build-system]
requires = ["maturin>=1.14.1,<2"]
build-backend = "maturin"

[tool.basedpyright]
stubPath = "stubs"

[tool.maturin]
module-name = "rynth"

[tool.maturin.generate-ci.github]
trusted-publishing = true
publishing-environment = "pypi"
pytest = true
zig = true

[tool.maturin.target.x86_64-apple-darwin]
# VapourSynth's minimum macOS target is 13.0.
macos-deployment-target = "13.0"

[tool.maturin.target.aarch64-apple-darwin]
# VapourSynth's minimum macOS target is 13.0.
macos-deployment-target = "13.0"

[tool.ruff]
extend-exclude = ["stubs"]

[tool.ruff.format]
line-ending = "lf"

[tool.uv]
cache-keys = [
    { file = "src/**/*.rs" },
    { file = "Cargo.lock" },
    { file = "Cargo.toml" },
    { file = "pyproject.toml" },
]
